// Demo clips data for testing
export const demoClips = [
  {
    "clip_id": "demo_001",
    "source_video_title": "Newsletter Hour 2026-02-18",
    "vizard_project_id": "demo_project_001",
    "clip_url": "https://sample-videos.com/video321/mp4/720/big_buck_bunny_720p_1mb.mp4",
    "title": "Breakthrough AI Marketing Strategy Revealed",
    "suggested_caption": "This clip showcases an incredible breakthrough in AI marketing that's transforming how businesses engage with customers. The viral potential is off the charts! 🚀 #AIMarketing #BusinessGrowth",
    "viral_score": "9",
    "transcript": "Today I want to share with you an incredible breakthrough in AI marketing. This is something that's going to completely transform the way you think about customer engagement...",
    "duration_ms": 45000,
    "status": "pending_review",
    "post_status": "not_posted",
    "created_at": "2026-02-20T18:30:00.000Z",
    "updated_at": "2026-02-20T18:30:00.000Z"
  },
  {
    "clip_id": "demo_002",
    "source_video_title": "Newsletter Hour 2026-02-18",
    "vizard_project_id": "demo_project_001",
    "clip_url": "https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/360/Big_Buck_Bunny_360_10s_1MB.mp4",
    "title": "The #1 Mistake Most Entrepreneurs Make",
    "suggested_caption": "Stop making this critical mistake! 99% of entrepreneurs fall into this trap and it's costing them millions. Learn the simple fix that changed everything for me. 💡",
    "viral_score": "8",
    "transcript": "The number one mistake I see entrepreneurs making every single day is this - they're focusing on the wrong metrics...",
    "duration_ms": 32000,
    "status": "pending_review",
    "post_status": "not_posted",
    "created_at": "2026-02-20T18:31:00.000Z",
    "updated_at": "2026-02-20T18:31:00.000Z"
  },
  {
    "clip_id": "demo_003",
    "source_video_title": "Tech Talk Tuesday 2026-02-19",
    "vizard_project_id": "demo_project_002",
    "clip_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    "title": "How We Scaled to $1M in 90 Days",
    "suggested_caption": "From zero to $1M in just 90 days! Here's the exact framework we used. No fluff, just results. This is the content everyone is talking about! 🔥💰 #Scaling #Entrepreneurship",
    "viral_score": "10",
    "transcript": "Let me walk you through the exact framework we used to scale from zero to one million dollars in revenue in just ninety days...",
    "duration_ms": 58000,
    "status": "approved",
    "post_status": "not_posted",
    "created_at": "2026-02-20T19:00:00.000Z",
    "updated_at": "2026-02-20T19:15:00.000Z"
  },
  {
    "clip_id": "demo_004",
    "source_video_title": "Tech Talk Tuesday 2026-02-19",
    "vizard_project_id": "demo_project_002",
    "clip_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    "title": "3 Tools That Changed My Business Forever",
    "suggested_caption": "These 3 tools literally changed everything. If you're not using them yet, you're leaving money on the table. Save this post! 📌✨",
    "viral_score": "7",
    "transcript": "I want to share three tools that completely transformed my business. The first one is something most people overlook...",
    "duration_ms": 41000,
    "status": "approved",
    "post_status": "not_posted",
    "created_at": "2026-02-20T19:02:00.000Z",
    "updated_at": "2026-02-20T19:16:00.000Z"
  },
  {
    "clip_id": "demo_005",
    "source_video_title": "Friday Funnel Review 2026-02-15",
    "vizard_project_id": "demo_project_003",
    "clip_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    "title": "Why Your Funnels Are Failing",
    "suggested_caption": "Your funnels are broken and here's why. Most people miss this ONE critical element. Watch til the end! 👀 #Funnels #Marketing",
    "viral_score": "6",
    "transcript": "If your funnels aren't converting, I can almost guarantee it's because of this one thing that everyone seems to forget...",
    "duration_ms": 28000,
    "status": "rejected",
    "post_status": "not_posted",
    "created_at": "2026-02-19T14:00:00.000Z",
    "updated_at": "2026-02-19T16:30:00.000Z"
  },
  {
    "clip_id": "demo_006",
    "source_video_title": "Monday Mastermind 2026-02-17",
    "vizard_project_id": "demo_project_004",
    "clip_url": "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
    "title": "The Future of AI in Local Business",
    "suggested_caption": "AI is revolutionizing local businesses RIGHT NOW. If you're not paying attention, you're already behind. Here's what you need to know today. 🤖🚀",
    "viral_score": "9",
    "transcript": "Artificial intelligence is completely revolutionizing the way local businesses operate, and if you're not paying attention...",
    "duration_ms": 52000,
    "status": "published",
    "post_status": "published",
    "published_at": "2026-02-18T20:00:00.000Z",
    "published_to_platforms": "TikTok, Instagram",
    "created_at": "2026-02-18T15:00:00.000Z",
    "updated_at": "2026-02-18T20:00:00.000Z"
  }
];
